Controllers/AdminHomepageController.cs
using HotelMS_ASP.NET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Net.Http.Headers;
using System.Text;

namespace HotelMS_ASP.NET_MVC.Controllers
{
    public class AdminHomepageController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly ILogger<AdminHomepageController> _logger; // Add ILogger

        public AdminHomepageController(ILogger<AdminHomepageController> logger)
        {

            //This part is to put in _httpCLient the URL of the API

            _httpClient = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:7102/Homepage")
            };
            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


            _logger = logger; // Initialize ILogger
        }



        //This Part is Responsible to GET REQUEST to WEB API which is responsible also to RETREIVE DATA to Database

        //READ
        public async Task<ActionResult> Index()
        {
            try
            {

                var response = await _httpClient.GetAsync("");

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.Hasauthorization = true;
                    ViewBag.Username = "admin";
                    var userAcc = await response.Content.ReadAsAsync<List<HomepageModel>>();
                    return View(userAcc);
                }
                else
                {
                    // Handle error response
                    return RedirectToAction("Index", "Home");
                }

            }
            catch (Exception ex)
            {
                // Handle exception
                return RedirectToAction("Index", "Home");
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoardingManagementSystemMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoardingManagementSystemMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!-- viewbag is from the controller which will became true of the user is already login -->
        <!--  then if "admin" this only the part will be show -->

        @if (ViewBag.Hasauthorization == true && ViewBag.Username == "admin")
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hotel Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminHomepage" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginAccess" asp-action="Index">LoginAccess</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HotelLog" asp-action="Index">HotelLog</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HotelRoom" asp-action="Index">HotelRoom</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-danger text-white"
                                   asp-area=""
                                   asp-controller="Home"
                                   asp-action="Logout"
                                   style="font-size: medium">Log Out</a>
                            </li>
                    </ul>
                </div>
            </div>
            </nav>
        }
        else if (ViewBag.Hasauthorization == true && ViewBag.Username == "user")
        {
            <!--  then if "admin" this only the part will be show -->
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library System</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">
                                <a class="btn btn-danger text-white"
                                   asp-area=""
                                   asp-controller="Home"
                                   asp-action="Logout"
                                   style="font-size: medium">Log Out</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BoardingManagementSystemMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>